#!/bin/usr/perl -w
use strict;
use diagnostics;
use utf8;
my @bases = ('A', 'B', 'W', 'X', 'Y' , 'Z');
print @bases, "\n";
print "@bases, \n";
exit;
my $base1 = pop @bases;
print  "an element removed from the end:\n $bases1, \n";
print @bases;
print "\n";
exit;
my $base2 = shift @bases;
print "an element removed from the beginning:\n $bases2, \n";
unshift (@bases, $base1);
print "@bases, \n";
exit;
push (@bases, $base2);
print "@bases, /n";
my @reverse = reverse @bases;
print "@reverse", "\n";
exit;
